name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
permissions:
  contents: write  # This is crucial!

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # Important!
          
      - uses: Platane/snk@v3
        with:
          github_user_name: MustafaHassan22
          svg_path: github-contribution-grid-snake.svg
          
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update snake animation"
          git push
